### ISSUE TITLE
matlab version

### ISSUE THREAD

**Issue by KengChiLiu** [kmaninis/COB#10]
Hi @kmaninis ,

What version of matlab are you using ? 
Do you know if other versions are okay too?
(Sorry I've never used matcaffe berfore)

**Comment by kmaninis** [comment]
Hi, I tried with MATLAB 2016b, Ubuntu 14.04. Could you give a more detailed explanation of the error that you are getting, so maybe I can help? Thanks.

**Comment by KengChiLiu** [comment]
Thanks @kmaninis ~ My problems appear at mattest
Error in caffe.set_mode_cpu (line 5)
caffe_('set_mode_cpu');
Error in caffe.run_tests (line 6)
caffe.set_mode_cpu();

By the way, I'm working on indoor image datasets recently. May I ask you for some few other questions?
(1) How do you calculate and normalize HHA images? Or just use them from other works ?
(2) Are there pre-computed SUNrgbd UCMs result?

Thank you so much~

**Comment by kmaninis** [comment]
Hi, to answer your questions:
(1) We use them for other works, however there is also [code](https://people.eecs.berkeley.edu/~sgupta/) that can be used to generate them.
(2) Yes there is, we did not upload it because it is not the best performing one on NYUD, but if you are interested I attach it [here](https://data.vision.ee.ethz.ch/kmaninis/share/COB/Downloads/COB_NYUD-v2_RGB.zip).

I hope it helps.

**Comment by KengChiLiu** [comment]
Thank you so much @kmaninis ~ 

My problem appears at mattest
Error in caffe.set_mode_cpu (line 5)
caffe_('set_mode_cpu');
Error in caffe.run_tests (line 6)
caffe.set_mode_cpu();

I've tried to solve it by https://github.com/BVLC/caffe/issues/3934 , but not working.
If you have any idea please tell me. If no, that's fine too. I'll keep trying.

By the way, one more thing, are there pre-computed SUNrgbd UCMs result? 

Thank you again~

**Comment by kmaninis** [comment]
Can you tell me what version of MATLAB, gcc, and Linux that you are using?

[This](https://github.com/BVLC/caffe/issues/3934#issuecomment-361966340) works nicely for most new versions.

**Comment by KengChiLiu** [comment]
@kmaninis 
MATLAB 2016a
gcc 5.4.0
Ubuntu 16.04

**Comment by kmaninis** [comment]
Ok, so, before starting MATLAB, please execute 
export LD_PRELOAD=$LD_PRELOAD:/usr/lib/x86_64-linux-gnu/libstdc++.so.6:/usr/lib/x86_64-linux-gnu/libprotobuf.so.9

on your bash. 

Please make sure to correctly locate the libraries (could be under a slightly different path)

**Comment by KengChiLiu** [comment]
Thanks @kmaninis 
It finally works !!!
I very appreciate for your help.

Note: For any who met "caffe_.mexw64: Invalid MEX-file" problem can solve by symbolic link or environment variable. It is caused by different env between Matlab and System.
