### ISSUE TITLE
Demo output of demo_cob_prop.m

### ISSUE THREAD

**Issue by msuc** [kmaninis/COB#11]
Hi guys,
I wanted to ask you if you (or someone else who made COB running) can verify the output of the demo program. I am not sure if the output "demo_cob_prop.m" produces the intended result. Compared to other examples it looks as some parts are missing which COB should capture (arms). I did not alter the code.

If you (someone) can maybe post the output of the demo, so that I am able to compare the results this would be great.

Thanks,
Markus
![cob_demo_output](https://user-images.githubusercontent.com/5889422/49497196-1789e380-f868-11e8-917e-28d5a22d0833.jpg)

**Comment by kmaninis** [comment]
Hi, this is the demo for object proposals, which has to do with the "objectness" of a combination of UCMs. The outputs is correct.
For detailed UCM outputs please run demo_cob_ucm.m

**Comment by msuc** [comment]
Thank you!
