### ISSUE TITLE
Output of COB

### ISSUE THREAD

**Issue by SensenHao** [kmaninis/COB#13]
Hello, thank you very much for sharing the code. Can you share the test results of the COB object proposal? I want to judge whether the result of my run is correct?

**Comment by kmaninis** [comment]
Hi, thank you for the kind words. You can download everything from here:
http://www.vision.ee.ethz.ch/~cvlsegmentation/cob/code.html

I hope it helps.

**Comment by SensenHao** [comment]
Thank you for your reply, take the liberty to ask a stupid question, "Pre-Computed COB Results" is the output of COB?
