### ISSUE TITLE
check failed: error == cudaSuccess(2 vs.  0) out of memory while testing

### ISSUE THREAD

**Issue by zihaog0724** [kmaninis/COB#15]
Hi, 
I'm tring to run just 1 image (batch size: 1) by using COB_PASCALContext_trainval.caffemodel and deploy.prototxt provided in this repo, but got the out-of-memory error. 

My hardware: Quadro P4000 with 8GB memories.

Does anyone know how to deal with this error? How many memories would COB use to run just 1 image? Thanks!

Appreciate any help

**Comment by kmaninis** [comment]
Hi, I remember that this depended on the version of Caffe. Are you using the suggested version? What happens if you lower the image resolution?
