### ISSUE TITLE
Typo on website : Retinal image underSANDING

### ISSUE THREAD

**Issue by theRealSuperMario** [kmaninis/COB#16]
Hi,

I just wanted to report that there seems to be a typo on the website http://people.ee.ethz.ch/~cvlsegmentation/

![image](https://user-images.githubusercontent.com/6517465/84129783-b5a0d000-aa42-11ea-8c13-a8c288b707bc.png)

Or maybe it is a feature, not a bug, and I don't undersand it. 

Cheers!

**Comment by kmaninis** [comment]
Thanks for the heads-up! Definitely not a feature!
