### ISSUE TITLE
Undefined function

### ISSUE THREAD

**Issue by zhangjingling** [kmaninis/COB#2]
when I run im2ucm.m  ,there is a error :
Undefined function 'loadvar' for input arguments of type 'char'.

**Comment by kmaninis** [comment]
Hi, thanks for your interest.  Installing the package (install.m) should do the work. loadvar is located under src/misc/. The install script includes this directory.

**Comment by zhangjingling** [comment]
Thank you for your answer! I am so exciting! I will have a try . thank you very much !
