### ISSUE TITLE
high-level segments from pre-computed proposals

### ISSUE THREAD

**Issue by ghost** [kmaninis/COB#4]
Hi,
Thanks for making the toolbox available. I was wondering if there is a way to go from the pre-computed proposals on MSCOCO to high-level meaningful segmentation as shown in your paper (but for some other dataset). Do you need caffee and GPU for that? Sorry I am fairly new to this field!

Thanks

**Comment by kmaninis** [comment]
Hi,
If I understand correctly, you are referring to the high-level experiments of the journal version of COB.
This process does not require GPU. It also does not require proposals. We snap the results of Semantic Segmentation to the superpixels generated by COB, using simple majority voting (i.e. the class that overlaps the most with the superpixel is assigned to it).

Please correct me if I misunderstood your question.

**Comment by ghost** [comment]
You understood perfectly. I am interested in getting semantic segments using deepmask for a subset of MSCOCO images. I tried accessing the pre-computed proposals but couldn't go far. I couldn't download and re-run the deepmask algorithm since it needs GPU, Caffee or some other deep learning toolbox. Correct me if I am wrong about this!! Is there a CPU way to get the results as shown in the journal, as in download and run it out of the box on the MSCOCO images? 

Appreciate the response.
Thanks

**Comment by kmaninis** [comment]
For DeepMask, we downloaded the pre-computed proposals from here: https://github.com/facebookresearch/deepmask.
However, we used them only for evaluation and not coupled with the pipeline of COB in the object proposals section.

We used snapping to COB superpixels for semantic segmentation instead. This does not require GPU once you have the pre-computed superpixels and semantic segmentation results.

I hope this helps.

**Comment by ghost** [comment]
I am sorry if I confused you. I am totally new to deep learning and therefore deepmask. I am working on semantic alignment for which I need good segmentation results for images.Here are the questions I have:
1. To run and get segmentation results from Deepmask on an image dataset, don't we need GPU and Caffe?
2. If yes, then am I correct in thinking that somewhere there are pre-computed segmentation results for the MSCOCO dataset?
3. If no, how can I run DeepMask on the subset of MSCOCO images? I do not need to train but simply run the model on the images from MSCOCO that I have. There are only 100 of them.

I really appreciate the prompt and helpful response.
Thanks

**Comment by kmaninis** [comment]
1. Yes, to run DeepMask you need to run their Torch implementation.
2. You can download their pre-computed proposals from here: https://github.com/facebookresearch/deepmask if you scroll to the bottom of the page, there are links to them.
3. For this, you would need to install the DeepMask code, but for that I can not help you much.

Hope this helps :)

**Comment by ghost** [comment]
okay, thanks a lot. I appreciate your help.
