### ISSUE TITLE
About segmentation benchmarking

### ISSUE THREAD

**Issue by nkwangyh** [kmaninis/COB#6]
Hi,
I'm new to this direction. And I have a few questions about how to benchmark on the NYUD-v2 dataset.
1. how do you get the segmentation groundtruth? I've downloaded the labeled data from NYUD-v2 website but there is no groundtruth but only 'labels' and 'instances' which may be used as groundtruth. But I don't know which one do you use in your paper.
2. What's more, if you use either 'labels' or 'instances', how do you dealing with the 'unlabeled' part(labeled as '0')?
3. The last question is that I find the size of 'ucm2' from you websize is '851x1121 double', which means segmentation result will be '425x560'. But resolutions of 'labels' and 'instances' are both standard '480x640' of Kinect.
Could you help me with the questions? Thank you very much.

**Comment by kmaninis** [comment]
Hi,
Thank you very much for your interest!

I remember also having the same questions with you, until I found that  Saurabh Gupta had made all pre-processed data available here: www.cs.berkeley.edu/~sgupta/eccv14/eccv14-data.tgz.

In general, all resources needed were obtained in this webpage: https://github.com/s-gupta/rcnn-depth

The pre-processing uses the 'instances', with proper handling of the '0' areas. They also cut the outer region of the images, which is the reason for the smaller resolution. The boundaries are recovered from the UCMs as ucm2(3:2:end, 3:2:end).

I hope this answers all of your concerns.

**Comment by nkwangyh** [comment]
Your reply is so quickly and the answers you give exactly solve my questions. Thank you very much!

**Comment by kmaninis** [comment]
Glad it helped!

The README was updated accordingly. Thanks for pointing this issue out.
