### ISSUE TITLE
bbox format

### ISSUE THREAD

**Issue by yuxinyan** [kmaninis/COB#7]
Question: The bbox coordinate of image's top-left is [0,0]. and the format of bbox is [y1, x1, y2, x2] corresponding to [up, left, down, right]. Is it right?

**Comment by kmaninis** [comment]
Hi, I guess you are referring to the bounding box proposals. The top-left of the image is [1, 1] (matlab indixes).  For the format you are right, it is [ymin, xmin, ymax, xmax].

**Comment by yuxinyan** [comment]
Thanks a lot!
