### ISSUE TITLE
the resnet model w/o bn

### ISSUE THREAD

**Issue by pkuCactus** [kmaninis/COB#8]
Hi @kmaninis ,

thanks for your sharing code, and where could i found the res50 caffemodel w/o bn, or you just use the res50 model with BN initialize the weights? Thanks again, expecting for reply.

**Comment by kmaninis** [comment]
Hi,
We indeed initialize the model from the resnet-50 with bn, from the official resnet repo. Hope it helps!

**Comment by pkuCactus** [comment]
@kmaninis Thanks for your reply， I'll try it.
